#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://node0011:3306/logs_static_result?serverTimezone=UTC&characterEncoding=utf-8
    password: password
    username: root

#配置mybatis信息

mybatis:
  type-aliases-package: cn.edu.neu.domain
  mapper-locations: classpath:mapper/*.xml
